matrix:
  fast_finish: true
  include:
#   - language: python
#     python: 3.4
#     os: linux
   - language: generic
     os: osx

env:
  pypi_pass:
    secure: uOKQJ3KxdWyhdhbwI3s5pAW6jKVMIRS5dWrMW7Rvsld7U6JedtHGDvmszFxqek2l+ImHYAUjCob9BGdVb7zHCu0qamp+v+GJKyovS7mC/s+JqeOyb9qi+F/qoUGD41IxSna05Mhbgqsf9FbSiVaj/Wo50jzP95EqfYmO6Hw/YlPaCjFx2YoPyc+gS/LJpLD3Uhp3diibjCwXgbPb4s5lXQhjIiXyPKqa41y1ynDVlBEIbURDOhWT344BVqg1bJIkrHAicTABI37nH7jQkfe1IIuwoMaRuyQZ82P7yuMmwJ3m+lO6GQbLLM1By0S6agU874XsGtOLS+SgBLmfCSFDTAiuftM8vA3IuSWyKqsITge2W43F+P+eLUR5eaDFF9Cxn0dvBodfBZzth/qhrCKf/C+kB5QKveuatA6Nd3dpzmflW+KOPkUrdK1lfwg1wM5GpsTt1xRIe1dewPBhXETMdsaDj+WJCzaKhg4zbLO24BPFvJMhVUM1lD5XQP1hIG73VMZ6eB/EwFrOaUPSQ5xQEJn5/Xlcht7HvjJPYXn6UE2L+PyAZeOLIsbFfYcf26yBrc1ovVY/tEej2guj5ZP2TMRP/X9/QGnPtOle1UgB2zwttNN5hXihorqxftsTdIbYtZIQ4+8QAkuATzmSEi/M4jvnxkPKwUljQWAGyB4y+1U=

install:

 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      yes | sudo add-apt-repository ppa:zoogie/sdl2-snapshots;
      yes | sudo add-apt-repository ppa:gstreamer-developers/ppa;
      sudo apt-get update;
      sudo apt-get -y install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev;
      sudo apt-get -y install libgstreamer1.0-dev gstreamer1.0-alsa gstreamer1.0-plugins-base gstreamer1.0-plugins-good;
      sudo apt-get -y install python-dev libsmpeg-dev libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff4-dev libX11-dev libmtdev-dev;
      sudo apt-get -y install python-setuptools build-essential libgl1-mesa-dev libgles2-mesa-dev;
      sudo apt-get -y install xvfb pulseaudio;
      pip install --upgrade cython pillow coveralls;
      pip install kivy;
      pip install mpf;
      pip install https://github.com/missionpinball/mpf/zipball/dev;
      python setup.py install;
   fi;

 - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      xcode-select --install;
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
      Brew install python3;
      pip3 install -I Cython==0.23;
      USE_OSX_FRAMEWORKS=0 pip3 install kivy;
      pip3 install wheel setuptools --upgrade;
      ls /usr/local/SDL2;
      USE_OSX_FRAMEWORKS=0 pip3 install .;

    fi;

before_script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      export DISPLAY=:99.0;
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX;
      export PYTHONPATH=$PYTHONPATH:$(pwd);
    fi;

#  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
#      export CC=clang;
#      export CXX=clang;
#      export FFLAGS=-ff2c;
#      export USE_OPENGL_MOCK=1;
#    fi;

script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      coverage run -m unittest discover -s mpfmc/tests;
    fi;

  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      echo skipping tests
    fi;

after_success:
 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
     coveralls
   fi;

  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      python3 setup.py bdist_wheel;
      cd dist;
      python3 ../build_scripts/rename_wheels.py;
      pip3 install twine;
      python3 -m twine upload -u brianmadden -p $pypi_pass --skip-existing *;
    fi;
