dist: trusty
sudo: required

matrix:
  fast_finish: true
  include:
   - os: linux
     env: LINUX=ubuntu:14.04
     sudo: required
     language: python
     python: "3.4"
   - os: linux
     env: LINUX=ubuntu:16.04
     sudo: required
     language: python
     python: "3.5"
   - os: linux
     env: LINUX=ubuntu:18.04
     sudo: required
     language: python
     python: "3.6"
   - os: linux  # oldstable
     env: LINUX=debian:jessie
     sudo: required
     language: python
     python: "3.4"
   - os: linux  # stable
     env: LINUX=debian:stretch
     sudo: required
     language: python
     python: "3.5"
   - os: linux  # testing
     env: LINUX=debian:buster
     sudo: required
     language: python
     python: "3.6"
   - os: osx
     language: generic
     osx_image: xcode8.3  # OS 10.12
   - os: osx
     language: generic
     osx_image: xcode8  # OS 10.11
   - os: osx
     language: generic
     osx_image: xcode6.4  # OS 10.10

services:
  - docker

before_install:
  - git clone --recursive --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf.git _mpf || git clone --recursive --branch `python3 get_version.py` https://github.com/missionpinball/mpf.git _mpf || git clone --recursive --branch dev https://github.com/missionpinball/mpf.git _mpf;
  - git clone --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf-debian-installer.git _mpf_installer || git clone --recursive --branch `python3 get_version.py` https://github.com/missionpinball/mpf-debian-installer.git _mpf_installer || git clone --recursive --branch dev https://github.com/missionpinball/mpf-debian-installer.git _mpf_installer;

install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      curl --progress-bar -S https://www.python.org/ftp/python/3.6.7/python-3.6.7-macosx10.6.pkg -o python-3.6.7-macosx10.6.pkg;
      sudo installer -pkg python-3.6.7-macosx10.6.pkg -target /;
      curl -sS https://bootstrap.pypa.io/get-pip.py > get-pip.py;
      sudo python3 get-pip.py;
    fi;
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      cd ${TRAVIS_BUILD_DIR};
      pip3 install setuptools Cython==0.26.1 --upgrade;
      brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer;
      git clone --recursive --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf.git _mpf || git clone --recursive --branch `python3 get_version.py` https://github.com/missionpinball/mpf.git _mpf || git clone --recursive --branch dev https://github.com/missionpinball/mpf.git _mpf;
      pip3 install -e _mpf/;
      pip3 install .;
    fi;

env:
  global:
     - secure: "WNvNRbHmintW6NlclAw3rbP4EzJ0Zt7gqVSha/+gC8Vo2pkbWphltgH5YwBGGM37ZRRbJ90Qm7aaLsFSpxOLnWlOlTw6/NBdKFEjvZISU8x7VcxlScNKTgDmeMYrDTsfbzoZJx7A6ZzxIm3fvRDcfhQcB0kI6wvLhcD1jHGqy0omfOHyFw51RfvRq07xsqavHN2Km9ObSqRCyMSuKNSCBHuIvGq7WnMfv+yU+iEV9pfQOEIo6JC7aySfIJ0gdgXK68RbWPLg1x4KwLsni9VDnOxXw9lPQbJfv9bpY1Fv3RWOQE763mHGojyorODrLCcYnKW+f177+h8PfBgIMMJdcF4CmanoGSrJG6QCp0GdauNzaqSXhGPFGIBToHPdFAW9XbHyVivFOP+rK8fo52euxX4rOgAF0oYuTxaz1SZn0x52u/BWG44Za9pQur8mZZHuZr9JpSzYF2u1FO3T4wj3noCBkXXe250WQp/zA1VrWgRPZgB9r6nxfguWsbzpia2dhcRDY+/jChJvc2mvHio8wlw3WhFhoUjUQkoGzmr/uio2j4SEo84wAClcQ5S6yzGY4IE8i8b4NZuJy9tsVS8+99TaR4TrUET1r+LqU7T4uN2Bp85zaw1ekmlj5xUD5/aJWagIM6kCv35nSD2camIQWVq0eiBqzOsu0npH9EhML0A="
     - USE_CYTHON: 1

script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      docker run -v $PWD:$PWD -v /dev/snd:/dev/snd --privileged -w $PWD $LINUX /bin/sh -c "_mpf_installer/install-mpf-dependencies && _mpf_installer/install-mc-dependencies && pip3 install --upgrade coveralls && pip3 install prospector && apt-get -y install xvfb && pip3 install -e _mpf/ && pip3 install -e . && export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX && export PYTHONPATH=$PYTHONPATH:$(pwd) && coverage3 run --concurrency=thread -m unittest discover -s mpfmc/tests && prospector && coverage3 run -a --concurrency=thread -m unittest discover -s mpfmc/integration;";
    fi;

after_success:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      coveralls;
    fi;

# commented out because we're not currently building wheels for Mac, but maybe
# that will change in the future? Reason is because there are no wheels for Kivy,
# so users need Cython and command line dev tools to build it, so why not just
# build MPF-MC too?

#  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
#      python3 setup.py bdist_wheel;
#      ls;
#      cd dist;
#      python3 ../build_scripts/rename_wheels.py;
#      pip3 install twine;
#      ls;
#      python3 -m twine upload -u brianmadden -p $PYPI_PASS --skip-existing *;
#    fi;
