dist: trusty
sudo: required

matrix:
  fast_finish: true
  include:
   - os: osx
     env: PYVERS="3.5.4 3.6.8 3.7.4"
     language: generic
     osx_image: xcode10
     name: "OSX - wheel generation"

services:
  - docker

before_install:
  - git clone --recursive --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf.git _mpf || git clone --recursive --branch `python3 get_version.py` https://github.com/missionpinball/mpf.git _mpf || git clone --recursive --branch dev https://github.com/missionpinball/mpf.git _mpf;
  - git clone --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf-debian-installer.git _mpf_installer || git clone --recursive --branch `python3 get_version.py` https://github.com/missionpinball/mpf-debian-installer.git _mpf_installer || git clone --recursive --branch dev https://github.com/missionpinball/mpf-debian-installer.git _mpf_installer;

  # https://github.com/travis-ci/travis-ci/issues/6307
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      travis_wait brew update;
      brew install gpg2;
      brew uninstall gpg;
      gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3;
      rvm get stable;
    fi

install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      curl --progress-bar -S https://www.python.org/ftp/python/3.6.7/python-3.6.7-macosx10.6.pkg -o python-3.6.7-macosx10.6.pkg;
      sudo installer -pkg python-3.6.7-macosx10.6.pkg -target /;
      curl -sS https://bootstrap.pypa.io/get-pip.py > get-pip.py;
      sudo python3 get-pip.py;

      curl -O -L https://github.com/aria2/aria2/releases/download/release-1.29.0/aria2-1.29.0-osx-darwin.dmg;
      hdiutil attach aria2-1.29.0-osx-darwin.dmg;
      sudo installer -package "/Volumes/aria2 1.29.0 Intel/aria2.pkg" -target /;

      curl -O -L https://www.libsdl.org/release/SDL2-2.0.9.dmg;
      curl -O -L https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.4.dmg;
      curl -O -L https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.dmg;
      curl -O -L https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.15.dmg;
      /usr/local/aria2/bin/aria2c -x 10 https://gstreamer.freedesktop.org/data/pkg/osx/1.10.2/gstreamer-1.0-1.10.2-x86_64.pkg;
      /usr/local/aria2/bin/aria2c -x 10 https://gstreamer.freedesktop.org/data/pkg/osx/1.10.2/gstreamer-1.0-devel-1.10.2-x86_64.pkg;

      hdiutil attach SDL2-2.0.9.dmg;
      sudo cp -a /Volumes/SDL2/SDL2.framework /Library/Frameworks/;
      hdiutil attach SDL2_image-2.0.4.dmg;
      sudo cp -a /Volumes/SDL2_image/SDL2_image.framework /Library/Frameworks/;
      hdiutil attach SDL2_ttf-2.0.15.dmg;
      sudo cp -a /Volumes/SDL2_ttf/SDL2_ttf.framework /Library/Frameworks/;
      hdiutil attach SDL2_mixer-2.0.4.dmg;
      sudo cp -a /Volumes/SDL2_mixer/SDL2_mixer.framework /Library/Frameworks/;
      sudo installer -package gstreamer-1.0-1.10.2-x86_64.pkg -target /;
      sudo installer -package gstreamer-1.0-devel-1.10.2-x86_64.pkg -target /;
    fi;

env:
  global:
     - secure: "WNvNRbHmintW6NlclAw3rbP4EzJ0Zt7gqVSha/+gC8Vo2pkbWphltgH5YwBGGM37ZRRbJ90Qm7aaLsFSpxOLnWlOlTw6/NBdKFEjvZISU8x7VcxlScNKTgDmeMYrDTsfbzoZJx7A6ZzxIm3fvRDcfhQcB0kI6wvLhcD1jHGqy0omfOHyFw51RfvRq07xsqavHN2Km9ObSqRCyMSuKNSCBHuIvGq7WnMfv+yU+iEV9pfQOEIo6JC7aySfIJ0gdgXK68RbWPLg1x4KwLsni9VDnOxXw9lPQbJfv9bpY1Fv3RWOQE763mHGojyorODrLCcYnKW+f177+h8PfBgIMMJdcF4CmanoGSrJG6QCp0GdauNzaqSXhGPFGIBToHPdFAW9XbHyVivFOP+rK8fo52euxX4rOgAF0oYuTxaz1SZn0x52u/BWG44Za9pQur8mZZHuZr9JpSzYF2u1FO3T4wj3noCBkXXe250WQp/zA1VrWgRPZgB9r6nxfguWsbzpia2dhcRDY+/jChJvc2mvHio8wlw3WhFhoUjUQkoGzmr/uio2j4SEo84wAClcQ5S6yzGY4IE8i8b4NZuJy9tsVS8+99TaR4TrUET1r+LqU7T4uN2Bp85zaw1ekmlj5xUD5/aJWagIM6kCv35nSD2camIQWVq0eiBqzOsu0npH9EhML0A="

before_script:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      export CC=clang;
      export CXX=clang;
      export FFLAGS=-ff2c;
      export KIVY_GL_BACKEND=mock;
    fi;

script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      docker run -v $PWD:$PWD -v /dev/snd:/dev/snd --privileged -w $PWD $LINUX /bin/sh -c "_mpf_installer/install-mpf-dependencies && _mpf_installer/install-mc-dependencies && pip3 install --upgrade coveralls && pip3 install prospector==1.1.6.3 && apt-get -y install xvfb && pip3 install -e _mpf/ && pip3 install -e . && export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX && export PYTHONPATH=$PYTHONPATH:$(pwd) && coverage3 run --concurrency=thread -m unittest discover -s mpfmc/tests && prospector && coverage3 run -a --concurrency=thread -m unittest discover -s mpfmc/integration;";
    fi;

  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    set -ex;

    mkdir ../wheelhouse;

    for pyver in $PYVERS; do
      git reset --hard;
      git clean -d -x -f;
      pyver_short=${pyver:0:3};

      curl -O -L https://www.python.org/ftp/python/$pyver/python-$pyver-macosx10.6.pkg;
      sudo installer -package python-$pyver-macosx10.6.pkg -target /;
      curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py;
      python$pyver_short get-pip.py --user;
      python$pyver_short -m pip install git+http://github.com/tito/osxrelocator --user;

      python$pyver_short -m pip install --upgrade --user pip setuptools wheel;
      python$pyver_short -m pip install --upgrade --user cython==0.29.10 pytest wheel pillow mock docutils twine;
      python$pyver_short -m pip install --upgrade delocate;

      python$pyver_short -m pip install -e _mpf/;

      USE_CYTHON=1 USE_SDL2=1 USE_GSTREAMER=1 python$pyver_short setup.py build_ext --inplace>output.txt;
      USE_CYTHON=1 USE_SDL2=1 USE_GSTREAMER=1 python$pyver_short setup.py bdist_wheel>output.txt;

      /Library/Frameworks/Python.framework/Versions/$pyver_short/bin/delocate-wheel dist/*.whl;
      zip_dir="$(basename dist/*.whl .whl)";
      unzip dist/*.whl -d dist/$zip_dir;
      echo "sleeping to let the full log display";
      sleep 10;
      ls dist/$zip_dir;
      rm dist/$zip_dir/mpfmc/.dylibs/libg*;
      rm dist/$zip_dir/mpfmc/.dylibs/GStreamer;
      cp /Library/Frameworks/SDL2_mixer.framework/Versions/A/Frameworks/FLAC.framework/Versions/A/FLAC dist/$zip_dir/kivy/.dylibs/;
      cp /Library/Frameworks/SDL2_ttf.framework/Versions/A/Frameworks/FreeType.framework/Versions/A/FreeType dist/$zip_dir/kivy/.dylibs/;
      cp /Library/Frameworks/SDL2_mixer.framework/Versions/A/Frameworks/Ogg.framework/Versions/A/Ogg dist/$zip_dir/kivy/.dylibs/;
      cp /Library/Frameworks/SDL2_mixer.framework/Versions/A/Frameworks/Vorbis.framework/Versions/A/Vorbis dist/$zip_dir/kivy/.dylibs/;
      cp /Library/Frameworks/SDL2_mixer.framework/Versions/A/Frameworks/modplug.framework/Versions/A/modplug dist/$zip_dir/kivy/.dylibs/;
      cp /Library/Frameworks/SDL2_mixer.framework/Versions/A/Frameworks/mpg123.framework/Versions/A/mpg123 dist/$zip_dir/kivy/.dylibs/;
      python$pyver_short -m osxrelocator.__init__ dist/$zip_dir/kivy/.dylibs @rpath/SDL2.framework/Versions/A/SDL2 @loader_path/SDL2>output.txt;
      python$pyver_short -m osxrelocator.__init__ dist/$zip_dir/kivy/.dylibs @rpath/FLAC.framework/Versions/A/FLAC @loader_path/FLAC>output.txt;
      python$pyver_short -m osxrelocator.__init__ dist/$zip_dir/kivy/.dylibs @rpath/modplug.framework/Versions/A/modplug @loader_path/modplug>output.txt;
      python$pyver_short -m osxrelocator.__init__ dist/$zip_dir/kivy/.dylibs @rpath/mpg123.framework/Versions/A/mpg123 @loader_path/mpg123>output.txt;
      python$pyver_short -m osxrelocator.__init__ dist/$zip_dir/kivy/.dylibs @rpath/FreeType.framework/Versions/A/FreeType @loader_path/FreeType;
      python$pyver_short -m osxrelocator.__init__ dist/$zip_dir/kivy/.dylibs @rpath/webp.framework/Versions/A/webp @loader_path/webp>output.txt;
      python$pyver_short -m osxrelocator.__init__ dist/$zip_dir/kivy/.dylibs @rpath/Vorbis.framework/Versions/A/Vorbis @loader_path/Vorbis>output.txt;
      python$pyver_short -m osxrelocator.__init__ dist/$zip_dir/kivy/.dylibs @rpath/../../../../SDL2.framework/Versions/A/SDL2 @loader_path/SDL2>output.txt;
      python$pyver_short -m osxrelocator.__init__ dist/$zip_dir/kivy/.dylibs @rpath/Ogg.framework/Versions/A/Ogg @loader_path/Ogg>output.txt;
      rm dist/$zip_dir.whl;
      pushd dist;
      python$pyver_short -c "from delocate import delocating; delocating.dir2zip('$zip_dir', '$zip_dir.whl')";
      rm -rf $zip_dir;
      popd;
      /Library/Frameworks/Python.framework/Versions/$pyver_short/bin/delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl;
      python$pyver_short -m ../build_scripts/rename_wheels.py;
      cp dist/*.whl ../wheelhouse/;
    done;

    ls ../wheelhouse/;
    python$pyver_short -m twine upload -u brianmadden -p $PYPI_PASS --skip-existing ../wheelhouse/*;

    fi;

after_success:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      coveralls;
    fi;

# commented out because we're not currently building wheels for Mac, but maybe
# that will change in the future? Reason is because there are no wheels for Kivy,
# so users need Cython and command line dev tools to build it, so why not just
# build MPF-MC too?

#  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
#      python3 setup.py bdist_wheel;
#      ls;
#      cd dist;
#      python3 ../build_scripts/rename_wheels.py;
#      pip3 install twine;
#      ls;
#      python3 -m twine upload -u brianmadden -p $PYPI_PASS --skip-existing *;
#    fi;
