language:
  python

matrix:
  fast_finish: true
  include:
  - python: "3.4"
    os: linux
  - python: "3.4"
    os: osx
  - python: "3.5"
    os: osx

install:

 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      yes | sudo add-apt-repository ppa:zoogie/sdl2-snapshots;
      yes | sudo add-apt-repository ppa:gstreamer-developers/ppa;
      sudo apt-get update;
      sudo apt-get -y install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev;
      sudo apt-get -y install libgstreamer1.0-dev gstreamer1.0-alsa gstreamer1.0-plugins-base gstreamer1.0-plugins-good;
      sudo apt-get -y install python-dev libsmpeg-dev libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff4-dev libX11-dev libmtdev-dev;
      sudo apt-get -y install python-setuptools build-essential libgl1-mesa-dev libgles2-mesa-dev;
      sudo apt-get -y install xvfb pulseaudio;
      pip install --upgrade cython pillow coveralls;
      pip install kivy;
      pip install mpf;
      pip install https://github.com/missionpinball/mpf/zipball/dev;
      python setup.py install;
   fi;

 - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      python3 -m pip install -U setuptools wheel pip mock;
      pip install https://github.com/missionpinball/mpf/zipball/dev;
      python3 -m pip install .;
      python3 setup.py bdist_wheel;
   fi;

before_script:
 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
    export DISPLAY=:99.0;
    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX;
    export PYTHONPATH=$PYTHONPATH:$(pwd);

   fi;

script:
 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
     coverage run -m unittest discover -s mpfmc/tests;
   fi;

after_success:
 - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
     coveralls
   fi;
