# AppVeyor config for MPF-MC
# This config based on https://packaging.python.org/en/latest/appveyor/

environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"

install:
  - "%PYTHON%\\python.exe -m pip install -U setuptools wheel pip mock"

  # todo get the latest mpf

  - "copy c:\\projects\\mpf-mc\\build_scripts\\distutils.cfg %PYTHON%\\Lib\\distutils\\distutils.cfg"
  - "%PYTHON%\\python.exe -m pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy"
  - "set USE_SDL2=1"
  - "set USE_GSTREAMER=1"
  - "%PYTHON%\\python.exe -m pip install cython docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew kivy.deps.gstreamer kivy.deps.glew_dev kivy.deps.sdl2_dev kivy.deps.gstreamer_dev --extra-index-url https://kivy.org/downloads/packages/simple/"

  - "%PYTHON%\\python.exe -m pip install .

build: off

test_script:
  - "%PYTHON%\\python.exe -m unittest discover mpfmc"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*