#config_version=4
mode:
  start_events: start_mode1
  stop_events: stop_mode1
  priority: 100
  start_priority: 1

widget_player:
  show_widget_mode1_on_slide_mode2:
    widget_mode1:
      slide: slide_mode2

widgets:
  widget_mode1:
    type: text
    text: Widget Mode 1
