#config_version=3

# The first line of every MPF config file needs to start with a hash sign,
# then config_version=3. When we add features that require changes to config
# files, we update the version number.

# You can add comments to config files by starting a line with a hash sign
# Comments are ignored by MPF and can be used for notes to yourself.





slides:
# The 'slides' section contains entries for named slides in your game. Then
# you can show any slide just by calling for that slide in a nice reusable way.

# Notice that each slide section is indented under the "slides:" section.

  slide1:  # This is the slide called "slide1"
    # Each slide has a list of "widgets" that are on it. Each widget is separated
    # by a dash.
    - type: text  # This is the first widget for slide1
      text: I AM A TEXT WIDGET ON SLIDE1 WITH DEFAULT SETTINGS
    - type: text  # This is the second widget
      text: HIT THE RIGHT ARROW KEY TO CONTINUE -->
      y: 33%
      animations:  # This widget has some animations for it.
        entrance:
          # The settings in the "entrance" section in the animations section
          # automatically start playing when the slide loads. Multiple steps in
          # the animation are also denoted with a dash.
          - property: opacity  # This step adjusts the "opacity" value of this widget.
            value: 0  # Zero means the widget is transparent
          - property: opacity  # This is the 2nd step in the animation. It also sets the opacity.
            value: 1  # But in this step, we're setting it back to 1 (opaque)
            repeat: true  # We add this so the animation repeats. Otherwise it would just run once.

  slide2:  # This is a different slide, called "slide2", etc.
    - type: text  # Every widget has a 'type', such as 'text', 'imagee', 'video', etc.
      text: I AM SLIDE 2. MY FONT SIZE IS 50
      font_size: 50  # Each type of widget has it's own settings. For example, font_size for text widgets
    - type: text
      text: HIT THE RIGHT ARROW KEY TO CONTINUE (MY FONT SIZE IS 15) -->
      y: 33%

  slide3:
    - type: text
      text: I AM SLIDE 3. I AM RED
      font_size: 50
      color: ff0000  # You can use standard hex colors for widgets
    - type: text
      text: AGAIN, RIGHT ARROW -->
      y: 33%
      x: 66%
    - type: text
      text: ( <-- ALSO LEFT ARROW GOES BACK)
      y: 33%
      x: 22%
      animations:  # For this animation, we're animating the "x" property.
        entrance:  # "x" is the x position of the widget (like x,y coordinates)
          - property: x
            value: 20%  # In step 1, we set x to 225
            duration: .25s
          - property: x
            value: 22%  # In step 2, we set it back to 200
            repeat: true  # and repeat!
            duration: 250ms

  slide4:
    - type: text
      text: THIS DEMO IS DRIVEN BY A STANDARD MPF CONFIG FILE
      font_size: 20
      color: ff0000
    - type: text
      text: IT'S IN THE FOLDER /mpf_mc/examples/demo/config/config.yaml
      font_size: 20
      color: 00ff00
      y: -50
    - type: text
      text: KEEP GOING. (WE'LL REMOVE THIS MESSAGE FROM NOW ON)
      y: 75%
    - type: text
      text: JUST KNOW YOU CAN ALWAYS HIT THE LEFT AND RIGHT ARROWS TO GO BACK AND FORTH
      y: 85%

  slide5:
    - type: text
      text: HEY, THAT WAS A SLIDE TRANSITION  # Transitions are set when a slide is requested (we'll get to that)
      font_size: 45
      color: ffaa00
    - type: text
      text: The transition was called "push", the direction is "right", and the duration is "1s"
      font_size: 20
      color: 00ff33
      y: -50

# Now we're done with the slides config. The next section is the 'slide_player'.
# The slide_player is how we make slides show. They "play" when a certain mpf event is posted

slide_player:

  # There are lots of entries in here. One for each event.
  # So when the event 'mc_reset_phase_3' is posted, the slide_player shows slide1.
  mc_reset_phase_3:
    slide: slide1

  show_slide1:
    slide: slide1

  show_slide2:
    slide: slide2

  show_slide3:
    slide: slide3

  show_slide4:
    slide: slide4

  show_slide5:
    slide: slide5
    transition:  # We can also specify slide transitions in the slide_player
      type: push


mc_scriptlets:
  demo_driver.DemoDriver

keyboard:
  right:
    mc_event: next_slide
  left:
    mc_event: prev_slide

displays:
  default:
    width: 800
    height: 600